# -*- coding: utf-8 -*-
"""KNN Class Lakalantas 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpCwMBo_seYnJvubsRvF3MR7WdKr_q3P
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

df = pd.read_excel("/content/DataSet_LakaLantas_2025.xlsx")

df.head()

df = df.drop(columns=["No"])

print(df.info())

df.describe()

ringkasan_model = pd.DataFrame({
    "Komponen": [
        "Algoritma",
        "Jumlah Tetangga (K)",
        "Distance Metric",
        "Weight",
        "Jumlah Fitur",
        "Jumlah Data Training",
        "Jumlah Data Testing"
    ],
    "Nilai": [
        "K-Nearest Neighbor",
        knn.n_neighbors,
        knn.metric,
        knn.weights,
        X_train.shape[1],
        X_train.shape[0],
        X_test.shape[0]
    ]
})

ringkasan_model

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

hasil = []

for i in range(1, 201):

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=i
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    knn = KNeighborsClassifier(n_neighbors=5)

    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    acc = accuracy_score(y_test, pred)

    hasil.append([i, acc])

hasil_epoch = pd.DataFrame(hasil, columns=["Percobaan", "Accuracy"])

hasil_epoch.head()

print("Rata-rata Accuracy :", hasil_epoch["Accuracy"].mean())

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(hasil_epoch["Percobaan"], hasil_epoch["Accuracy"])
plt.xlabel("Percobaan")
plt.ylabel("Accuracy")
plt.title("Accuracy Selama 200 Percobaan KNN")
plt.grid(True)
plt.show()

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=knn.classes_
)

disp.plot(cmap="Blues", values_format="d")

plt.title("Confusion Matrix KNN")
plt.show()